allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": false
  "@tree-sitter-grammars/tree-sitter-yaml": false
  core-js-pure: false
  esbuild: true
  prisma: true
  tree-sitter: false
  tree-sitter-json: false
  unrs-resolver: true
