import type { DevicePlatform, DeviceStatus, UserRole } from "@/generated/prisma/enums";
import type { CommandStatus } from "@/types/contracts/command-status";

type DeviceAppState = "ENABLED" | "DISABLED";

export const copy = {
  appRole: "وب‌اپ فرزند و مراقب",
  dashboardTitle: "خانواده‌ها و دستگاه‌ها",
  members: "اعضا",
  devices: "دستگاه‌ها",
  noFamilies: "هنوز خانواده‌ای ثبت نشده است.",
  noDevices: "دستگاهی به این خانواده وصل نشده است.",
  noMembers: "عضوی در این خانواده ثبت نشده است.",
  lastSeen: "آخرین ارتباط",
  neverSeen: "هنوز ارتباطی ثبت نشده",
  databaseUnavailable: "اتصال به پایگاه داده برقرار نشد.",
  loginTitle: "ورود",
  registerTitle: "ساخت حساب",
  email: "ایمیل",
  password: "رمز عبور",
  firstName: "نام",
  lastName: "نام خانوادگی",
  submitLogin: "ورود",
  submitRegister: "ساخت حساب",
  noAccount: "حساب ندارید؟",
  hasAccount: "حساب دارید؟",
  logout: "خروج",
  createFamily: "خانواده جدید",
  familyName: "نام خانواده",
  saveFamily: "ساخت خانواده",
  inviteMember: "افزودن عضو",
  inviteEmail: "ایمیل عضو",
  role: "نقش",
  saveInvite: "افزودن",
  enrollmentTitle: "عضویت دستگاه والد",
  createEnrollment: "ساخت کد یک‌بارمصرف",
  enrollmentExpires: "اعتبار تا",
  enrollmentQrAlt: "کد عضویت دستگاه",
  openFamily: "مشاهده خانواده",
  openDevice: "مشاهده دستگاه",
  backToFamily: "بازگشت به خانواده",
  deviceDashboardTitle: "داشبورد دستگاه والد",
  connectionStatus: "وضعیت اتصال",
  battery: "باتری",
  storage: "حافظه",
  androidVersion: "نسخه اندروید",
  model: "مدل",
  manufacturer: "سازنده",
  deviceOwnerStatus: "وضعیت Device Owner",
  batteryCharging: "در حال شارژ",
  batteryNotCharging: "بدون شارژ",
  storageUsed: "مصرف‌شده",
  storageFree: "آزاد",
  valueUnknown: "نامشخص",
  openApps: "مدیریت برنامه‌ها",
  appsTitle: "برنامه‌های دستگاه",
  appsEmpty: "برنامه‌ای روی این دستگاه ثبت نشده است.",
  installApp: "نصب برنامه",
  uninstallApp: "حذف",
  enableApp: "فعال‌سازی",
  disableApp: "غیرفعال‌سازی",
  packageName: "نام بسته",
  appVersion: "نسخه",
  appStatus: "وضعیت برنامه",
  commandStatus: "وضعیت فرمان",
  selectAppToInstall: "انتخاب برنامه برای نصب",
  confirmUninstallTitle: "حذف برنامه",
  confirmUninstallBody: "این برنامه از گوشی والد حذف می‌شود. ادامه می‌دهید؟",
  confirmAction: "تأیید",
  cancelAction: "انصراف",
  noInstallCandidates: "برنامه قابل نصبی باقی نمانده است.",
  waitingForDevice: "در انتظار نتیجه گوشی والد…",
  unsupportedAction: "این عملیات برای این برنامه پشتیبانی نمی‌شود.",
  systemAppHint: "برنامه سیستمی",
  recentCommands: "فرمان‌های اخیر",
  commandsTitle: "صف فرمان‌ها",
  commandsEmpty: "فرمانی در صف نیست.",
  commandId: "شناسه فرمان",
  createdAt: "زمان ایجاد",
  expiresAt: "انقضا",
  cancelCommand: "لغو فرمان",
  openCommands: "صف فرمان‌ها",
  liveUpdatesConnected: "به‌روزرسانی زنده فعال است",
  openLocation: "موقعیت و ژئوفنس",
  openContacts: "مخاطبین",
  openSettings: "تنظیمات دستگاه",
  contactsTitle: "مخاطبین دستگاه",
  contactsEmpty: "مخاطبی ثبت نشده است.",
  searchContacts: "جستجوی مخاطب",
  addContact: "افزودن مخاطب",
  editContact: "ویرایش مخاطب",
  deleteContact: "حذف مخاطب",
  contactDisplayName: "نام",
  contactPhoneNumber: "شماره تلفن",
  saveContact: "ذخیره مخاطب",
  confirmDeleteContactBody: "این مخاطب از گوشی والد حذف می‌شود. ادامه می‌دهید؟",
  settingsTitle: "تنظیمات دستگاه والد",
  settingsEmpty: "تنظیم پشتیبانی‌شده‌ای گزارش نشده است.",
  settingsUnsupported: "این دستگاه گزارش تنظیمات را پشتیبانی نمی‌کند.",
  refreshSettings: "دریافت تنظیمات از دستگاه",
  settingReadOnly: "فقط خواندنی",
  settingInactive: "غیرفعال (پشتیبانی نمی‌شود)",
  saveSetting: "اعمال تنظیم",
  locationTitle: "موقعیت دستگاه",
  currentLocation: "موقعیت فعلی",
  lastLocationUpdate: "آخرین به‌روزرسانی موقعیت",
  locationPermission: "وضعیت مجوز موقعیت",
  locationService: "وضعیت سرویس موقعیت",
  locationUnavailable: "موقعیت در دسترس نیست.",
  locationAvailable: "موقعیت در دسترس است.",
  geofencesTitle: "ژئوفنس‌ها",
  geofencesEmpty: "هنوز ژئوفنسی ثبت نشده است.",
  createGeofence: "ساخت ژئوفنس",
  editGeofence: "ویرایش ژئوفنس",
  deleteGeofence: "حذف ژئوفنس",
  geofenceName: "نام ژئوفنس",
  latitude: "عرض جغرافیایی",
  longitude: "طول جغرافیایی",
  radiusMeters: "شعاع (متر)",
  searchLocation: "جستجوی مکان",
  searchAction: "جستجو",
  enabled: "فعال",
  disabled: "غیرفعال",
  lastEvent: "آخرین رویداد",
  lastEventTime: "زمان آخرین رویداد",
  noEventYet: "هنوز رویدادی ثبت نشده",
  notificationsTitle: "اعلان‌های خانواده",
  notificationsEmpty: "اعلانی وجود ندارد.",
  markRead: "خواندم",
  saveGeofence: "ذخیره",
  memberCount: "عضو",
  deviceCount: "دستگاه",
  unexpectedError: "درخواست انجام نشد.",
} as const;

export const roleLabels = {
  OWNER: "مالک",
  CAREGIVER: "مراقب",
  TECHNICAL_HELPER: "پشتیبان فنی",
  VIEWER: "بیننده",
} as const satisfies Record<UserRole, string>;

export const deviceStatusLabels = {
  PENDING: "در انتظار",
  ONLINE: "آنلاین",
  OFFLINE: "آفلاین",
  DISABLED: "غیرفعال",
} as const satisfies Record<DeviceStatus, string>;

export const deviceOwnerLabels = {
  true: "فعال",
  false: "غیرفعال",
  unknown: "نامشخص",
} as const;

export const deviceAppStateLabels = {
  ENABLED: "فعال",
  DISABLED: "غیرفعال",
} as const satisfies Record<DeviceAppState, string>;

export const commandStatusLabels = {
  PENDING: "در انتظار",
  SENT: "در حال اجرا",
  RECEIVED: "در حال اجرا",
  EXECUTING: "در حال اجرا",
  SUCCESS: "موفق",
  FAILED: "ناموفق",
  UNSUPPORTED: "پشتیبانی‌نشده",
  EXPIRED: "منقضی",
  CANCELLED: "لغو شده",
} as const satisfies Record<CommandStatus, string>;

export const platformLabels = {
  ANDROID: "اندروید",
} as const satisfies Record<DevicePlatform, string>;

export const locationPermissionLabels = {
  UNKNOWN: "نامشخص",
  PROMPT: "در انتظار تأیید",
  GRANTED: "مجاز",
  DENIED: "رد شده",
} as const;

export const locationServiceLabels = {
  true: "روشن",
  false: "خاموش",
  unknown: "نامشخص",
} as const;

export const geofenceEventLabels = {
  ENTERED: "ورود",
  EXITED: "خروج",
} as const;

export const deviceSettingSectionLabels = {
  DEVICE: "دستگاه",
  NETWORK: "شبکه",
  DISPLAY: "نمایش",
  SOUND: "صدا",
  SECURITY: "امنیت",
  APPLICATIONS: "برنامه‌ها",
} as const;

export const deviceSettingKeyLabels = {
  device_name: "نام دستگاه",
  screen_timeout_seconds: "خاموش شدن صفحه (ثانیه)",
  developer_options: "گزینه‌های توسعه‌دهنده",
  wifi_enabled: "وای‌فای",
  mobile_data_enabled: "دیتای موبایل",
  airplane_mode: "حالت هواپیما",
  brightness: "روشنایی",
  auto_brightness: "روشنایی خودکار",
  font_scale: "اندازه قلم",
  ring_volume: "صدای زنگ",
  media_volume: "صدای رسانه",
  do_not_disturb: "مزاحم نشوید",
  screen_lock_enabled: "قفل صفحه",
  unknown_sources: "منابع ناشناس",
  install_unknown_apps: "نصب برنامه‌های ناشناس",
  auto_update_apps: "به‌روزرسانی خودکار برنامه‌ها",
} as const;
