import type { DevicePlatform, DeviceStatus, UserRole } from "@/generated/prisma/enums";
import type { CommandType } from "@/types/contracts/command";
import type { CommandStatus } from "@/types/contracts/command-status";

type DeviceAppState = "ENABLED" | "DISABLED";

export const copy = {
  appRole: "وب‌اپ فرزند و مراقب",
  dashboardTitle: "خانواده‌ها و دستگاه‌ها",
  members: "اعضا",
  devices: "دستگاه‌ها",
  noFamilies: "هنوز خانواده‌ای ثبت نشده است.",
  noDevices: "دستگاهی به این خانواده وصل نشده است.",
  noMembers: "عضوی در این خانواده ثبت نشده است.",
  lastSeen: "آخرین ارتباط",
  neverSeen: "هنوز ارتباطی ثبت نشده",
  databaseUnavailable: "اتصال به پایگاه داده برقرار نشد.",
  loginTitle: "ورود",
  registerTitle: "ساخت حساب",
  welcomeBack: "خوش آمدید",
  welcomeCreate: "ساخت حساب جدید",
  authWelcomeLead: "مراقبت از والدین، ساده‌تر از همیشه",
  email: "ایمیل",
  password: "رمز عبور",
  firstName: "نام",
  lastName: "نام خانوادگی",
  submitLogin: "ورود",
  submitRegister: "ساخت حساب",
  noAccount: "حساب ندارید؟",
  hasAccount: "حساب دارید؟",
  logout: "خروج",
  createFamily: "خانواده جدید",
  familyName: "نام خانواده",
  saveFamily: "ساخت خانواده",
  inviteMember: "افزودن عضو",
  inviteEmail: "ایمیل عضو",
  role: "نقش",
  saveInvite: "افزودن",
  enrollmentTitle: "کد عضویت گوشی والد",
  createEnrollment: "کد عضویت جدید",
  enrollmentHint: "در اپ گوشی والد، کد را وارد یا QR را اسکن کنید. کد ۱۰ دقیقه اعتبار دارد و یک‌بارمصرف است.",
  enrollmentExpires: "اعتبار تا",
  enrollmentQrAlt: "کد عضویت دستگاه",
  copyEnrollmentCode: "کپی کد",
  enrollmentDone: "تمام",
  codeCopied: "کد کپی شد",
  youSuffix: "(شما)",
  deviceManagement: "مدیریت دستگاه",
  onMap: "روی نقشه",
  lastLocation: "آخرین موقعیت",
  tapMapHint: "روی نقشه بزنید تا ساخت محدودهٔ امن شروع شود.",
  drawAreaHint: "نقشه را جابه‌جا کنید؛ یک‌بار برای مرکز و بار دوم برای شعاع روی نقشه بزنید.",
  searchNoResults: "مکانی پیدا نشد. نام دقیق‌تری امتحان کنید.",
  searchPickResult: "یک نتیجه را انتخاب کنید",
  searchingLocation: "در حال جستجو…",
  loadingMap: "در حال بارگذاری نقشه…",
  mapAttribution: "نقشهٔ رایگان OpenStreetMap",
  deviceLocationMarker: "موقعیت دستگاه",
  drawnRadiusLabel: "شعاع انتخاب‌شده",
  metersUnit: "متر",
  notificationNew: "جدید",
  appsSubtitlePrefix: "برنامه‌های",
  connectedSince: "متصل از",
  moduleAppsHint: "نصب، حذف و فعال‌سازی",
  moduleContactsHint: "افزودن و ویرایش",
  moduleLocationHint: "نقشه و محدوده‌های امن",
  moduleSettingsHint: "وای‌فای، زنگ و بیشتر",
  moduleCommandsHint: "پیگیری کارهای ارسال‌شده",
  storageOf: "از",
  openFamily: "مشاهده خانواده",
  openDevice: "مشاهده دستگاه",
  backToFamily: "بازگشت به خانواده",
  backToDevice: "بازگشت به دستگاه",
  backToDashboard: "بازگشت به خانواده‌ها",
  deviceDashboardTitle: "داشبورد دستگاه والد",
  connectionStatus: "وضعیت اتصال",
  battery: "باتری",
  storage: "حافظه",
  androidVersion: "نسخه اندروید",
  model: "مدل",
  manufacturer: "سازنده",
  deviceOwnerStatus: "وضعیت Device Owner",
  batteryCharging: "در حال شارژ",
  batteryNotCharging: "بدون شارژ",
  storageUsed: "مصرف‌شده",
  storageFree: "آزاد",
  valueUnknown: "نامشخص",
  openApps: "مدیریت برنامه‌ها",
  appsTitle: "برنامه‌های دستگاه",
  appsEmpty: "برنامه‌ای روی این دستگاه ثبت نشده است.",
  installApp: "نصب برنامه",
  uninstallApp: "حذف",
  enableApp: "فعال‌سازی",
  disableApp: "غیرفعال‌سازی",
  packageName: "نام بسته",
  appVersion: "نسخه",
  appStatus: "وضعیت برنامه",
  commandStatus: "وضعیت فرمان",
  selectAppToInstall: "انتخاب برنامه برای نصب",
  confirmUninstallTitle: "حذف برنامه",
  confirmUninstallBody: "این برنامه از گوشی والد حذف می‌شود. ادامه می‌دهید؟",
  confirmAction: "تأیید",
  cancelAction: "انصراف",
  noInstallCandidates: "برنامه قابل نصبی باقی نمانده است.",
  waitingForDevice: "در انتظار نتیجه گوشی والد…",
  unsupportedAction: "این عملیات برای این برنامه پشتیبانی نمی‌شود.",
  systemAppHint: "برنامه سیستمی",
  recentCommands: "فرمان‌های اخیر",
  commandsTitle: "صف فرمان‌ها",
  commandsEmpty: "فرمانی در صف نیست.",
  commandId: "شناسه فرمان",
  createdAt: "زمان ایجاد",
  expiresAt: "انقضا",
  cancelCommand: "لغو فرمان",
  openCommands: "صف فرمان‌ها",
  liveUpdatesConnected: "به‌روزرسانی زنده فعال است",
  openLocation: "موقعیت و محدوده‌های امن",
  openContacts: "مخاطبین",
  openSettings: "تنظیمات دستگاه",
  contactsTitle: "مخاطبین دستگاه",
  contactsEmpty: "مخاطبی ثبت نشده است.",
  searchContacts: "جستجوی مخاطب",
  addContact: "افزودن مخاطب",
  editContact: "ویرایش مخاطب",
  deleteContact: "حذف مخاطب",
  contactDisplayName: "نام",
  contactPhoneNumber: "شماره تلفن",
  saveContact: "ذخیره مخاطب",
  confirmDeleteContactBody: "این مخاطب از گوشی والد حذف می‌شود. ادامه می‌دهید؟",
  settingsTitle: "تنظیمات دستگاه والد",
  settingsEmpty: "تنظیم پشتیبانی‌شده‌ای گزارش نشده است.",
  settingsUnsupported: "این دستگاه گزارش تنظیمات را پشتیبانی نمی‌کند.",
  refreshSettings: "دریافت تنظیمات از دستگاه",
  settingReadOnly: "فقط خواندنی",
  settingInactive: "غیرفعال (پشتیبانی نمی‌شود)",
  saveSetting: "اعمال تنظیم",
  locationTitle: "موقعیت دستگاه",
  currentLocation: "موقعیت فعلی",
  lastLocationUpdate: "آخرین به‌روزرسانی موقعیت",
  locationPermission: "وضعیت مجوز موقعیت",
  locationService: "وضعیت سرویس موقعیت",
  locationUnavailable: "موقعیت در دسترس نیست.",
  locationAvailable: "موقعیت در دسترس است.",
  geofencesTitle: "محدوده‌های امن",
  geofencesEmpty: "هنوز محدودهٔ امنی ثبت نشده است.",
  createGeofence: "ساخت محدودهٔ امن",
  editGeofence: "ویرایش محدودهٔ امن",
  deleteGeofence: "حذف محدودهٔ امن",
  geofenceName: "نام محدوده",
  latitude: "عرض جغرافیایی",
  longitude: "طول جغرافیایی",
  radiusMeters: "شعاع (متر)",
  searchLocation: "جستجوی مکان",
  searchAction: "جستجو",
  enabled: "فعال",
  disabled: "غیرفعال",
  lastEvent: "آخرین رویداد",
  lastEventTime: "زمان آخرین رویداد",
  noEventYet: "هنوز رویدادی ثبت نشده",
  notificationsTitle: "اعلان‌های خانواده",
  notificationsEmpty: "اعلانی وجود ندارد.",
  markRead: "خواندم",
  saveGeofence: "ذخیره",
  memberCount: "عضو",
  deviceCount: "دستگاه",
  unexpectedError: "درخواست انجام نشد.",
  installAppTitle: "نصب روی گوشی",
  installAppHint: "برای دسترسی سریع‌تر، اپ را به صفحهٔ اصلی اضافه کنید.",
  installAppAction: "نصب اپ",
  installIosTitle: "افزودن به صفحهٔ اصلی",
  installIosStepShare: "۱. دکمهٔ Share (مربع با فلش بالا) را در نوار پایین Safari بزنید.",
  installIosStepAdd: "۲. گزینهٔ Add to Home Screen / افزودن به صفحهٔ اصلی را انتخاب کنید.",
  installIosStepConfirm: "۳. روی Add / افزودن بزنید تا آیکون اپ روی صفحهٔ اصلی بیاید.",
  installDismiss: "الان نه",
  installGotIt: "متوجه شدم",
} as const;

export const roleLabels = {
  OWNER: "مالک",
  CAREGIVER: "مراقب",
  TECHNICAL_HELPER: "پشتیبان فنی",
  VIEWER: "بیننده",
} as const satisfies Record<UserRole, string>;

export const deviceStatusLabels = {
  PENDING: "در انتظار",
  ONLINE: "آنلاین",
  OFFLINE: "آفلاین",
  DISABLED: "غیرفعال",
} as const satisfies Record<DeviceStatus, string>;

export const deviceOwnerLabels = {
  true: "فعال",
  false: "غیرفعال",
  unknown: "نامشخص",
} as const;

export const deviceAppStateLabels = {
  ENABLED: "فعال",
  DISABLED: "غیرفعال",
} as const satisfies Record<DeviceAppState, string>;

export const commandStatusLabels = {
  PENDING: "در انتظار",
  SENT: "در حال اجرا",
  RECEIVED: "در حال اجرا",
  EXECUTING: "در حال اجرا",
  SUCCESS: "موفق",
  FAILED: "ناموفق",
  UNSUPPORTED: "پشتیبانی‌نشده",
  EXPIRED: "منقضی",
  CANCELLED: "لغو شده",
} as const satisfies Record<CommandStatus, string>;

export const commandTypeLabels = {
  GET_DEVICE_INFO: "دریافت اطلاعات دستگاه",
  GET_BATTERY: "دریافت باتری",
  GET_STORAGE: "دریافت حافظه",
  CREATE_CONTACT: "افزودن مخاطب",
  UPDATE_CONTACT: "ویرایش مخاطب",
  DELETE_CONTACT: "حذف مخاطب",
  GET_INSTALLED_APPS: "دریافت برنامه‌ها",
  INSTALL_APP: "نصب برنامه",
  UNINSTALL_APP: "حذف برنامه",
  ENABLE_APP: "فعال‌سازی برنامه",
  DISABLE_APP: "غیرفعال‌سازی برنامه",
  GET_LOCATION: "دریافت موقعیت",
  CREATE_GEOFENCE: "ساخت محدودهٔ امن",
  UPDATE_GEOFENCE: "ویرایش محدودهٔ امن",
  DELETE_GEOFENCE: "حذف محدودهٔ امن",
  GET_SETTINGS: "دریافت تنظیمات",
  SET_SETTING: "اعمال تنظیم",
} as const satisfies Record<CommandType, string>;

export const platformLabels = {
  ANDROID: "اندروید",
} as const satisfies Record<DevicePlatform, string>;

export const locationPermissionLabels = {
  UNKNOWN: "نامشخص",
  PROMPT: "در انتظار تأیید",
  GRANTED: "مجاز",
  DENIED: "رد شده",
} as const;

export const locationServiceLabels = {
  true: "روشن",
  false: "خاموش",
  unknown: "نامشخص",
} as const;

export const geofenceEventLabels = {
  ENTERED: "ورود",
  EXITED: "خروج",
} as const;

export const deviceSettingSectionLabels = {
  DEVICE: "دستگاه",
  NETWORK: "شبکه",
  DISPLAY: "نمایش",
  SOUND: "صدا",
  SECURITY: "امنیت",
  APPLICATIONS: "برنامه‌ها",
} as const;

export const deviceSettingKeyLabels = {
  device_name: "نام دستگاه",
  screen_timeout_seconds: "خاموش شدن صفحه (ثانیه)",
  developer_options: "گزینه‌های توسعه‌دهنده",
  wifi_enabled: "وای‌فای",
  mobile_data_enabled: "دیتای موبایل",
  airplane_mode: "حالت هواپیما",
  brightness: "روشنایی",
  auto_brightness: "روشنایی خودکار",
  font_scale: "اندازه قلم",
  ring_volume: "صدای زنگ",
  media_volume: "صدای رسانه",
  do_not_disturb: "مزاحم نشوید",
  screen_lock_enabled: "قفل صفحه",
  unknown_sources: "منابع ناشناس",
  install_unknown_apps: "نصب برنامه‌های ناشناس",
  auto_update_apps: "به‌روزرسانی خودکار برنامه‌ها",
} as const;
